"""Modern asynchronous Python client library for the Habitica API."""

from .const import ASSETS_URL, DEFAULT_URL, __version__
from .exceptions import (
    BadRequestError,
    HabiticaException,
    NotAuthorizedError,
    NotFoundError,
    TooManyRequestsError,
)
from .lib import Habitica
from .types import (
    Attributes,
    Direction,
    Frequency,
    HabiticaClass,
    HabiticaClassSystemResponse,
    HabiticaErrorResponse,
    HabiticaLoginResponse,
    HabiticaResponse,
    HabiticaScoreResponse,
    HabiticaSleepResponse,
    HabiticaStatsResponse,
    HabiticaTagResponse,
    HabiticaTagsResponse,
    HabiticaTaskOrderResponse,
    HabiticaTaskResponse,
    HabiticaTasksResponse,
    HabiticaUserExport,
    HabiticaUserResponse,
    Language,
    Skill,
    Task,
    TaskFilter,
    TaskType,
    UserStyles,
)

__all__ = [
    "__version__",
    "ASSETS_URL",
    "Attributes",
    "BadRequestError",
    "DEFAULT_URL",
    "Direction",
    "Frequency",
    "Habitica",
    "HabiticaClass",
    "HabiticaClassSystemResponse",
    "HabiticaErrorResponse",
    "HabiticaException",
    "HabiticaLoginResponse",
    "HabiticaResponse",
    "HabiticaScoreResponse",
    "HabiticaSleepResponse",
    "HabiticaStatsResponse",
    "HabiticaTagResponse",
    "HabiticaTagsResponse",
    "HabiticaTaskOrderResponse",
    "HabiticaTaskResponse",
    "HabiticaTasksResponse",
    "HabiticaUserExport",
    "HabiticaUserResponse",
    "Language",
    "NotAuthorizedError",
    "NotFoundError",
    "Skill",
    "Task",
    "TaskFilter",
    "TaskType",
    "TooManyRequestsError",
    "UserStyles",
]
